<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.dnS3PVd' shared service.

return $this->privates['.service_locator.dnS3PVd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'coursRepository' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService.php', true],
]);
