<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ow6O9tX' shared service.

return $this->privates['.service_locator.ow6O9tX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'categoryCour' => ['privates', 'App\\Entity\\CategoryCours', 'getCategoryCoursService.php', true],
]);
