<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ny4y38j' shared service.

return $this->privates['.service_locator.ny4y38j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'categoryCoursRepository' => ['privates', 'App\\Repository\\CategoryCoursRepository', 'getCategoryCoursRepositoryService.php', true],
    'paginator' => ['privates', '.errored..service_locator.ny4y38j.Knp\\Component\\Pager\\Pagination\\PaginationInterface', NULL, 'Cannot autowire service ".service_locator.ny4y38j": it references interface "Knp\\Component\\Pager\\Pagination\\PaginationInterface" but no such service exists. Did you create a class that implements this interface?'],
]);
