<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.ny4y38j.Knp\Component\Pager\Pagination\PaginationInterface' shared service.

include_once $this->targetDirs[3].'\\vendor\\knplabs\\knp-components\\src\\Knp\\Component\\Pager\\Pagination\\PaginationInterface.php';

return $this->privates['.errored..service_locator.ny4y38j.Knp\\Component\\Pager\\Pagination\\PaginationInterface'] = new \Knp\Component\Pager\Pagination\PaginationInterface();
