<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.6R9gNN2' shared service.

return $this->privates['.service_locator.6R9gNN2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'question' => ['privates', 'App\\Entity\\Question', 'getQuestionService.php', true],
]);
