<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.GgSa1Ig', 'get_ServiceLocator_GgSa1IgService.php', true],
    'App\\Controller\\CategoryController::show' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\CategoryCoursController::delete' => ['privates', '.service_locator.ow6O9tX', 'get_ServiceLocator_Ow6O9tXService.php', true],
    'App\\Controller\\CategoryCoursController::edit' => ['privates', '.service_locator.ow6O9tX', 'get_ServiceLocator_Ow6O9tXService.php', true],
    'App\\Controller\\CategoryCoursController::index' => ['privates', '.service_locator.UzvzYfm', 'get_ServiceLocator_UzvzYfmService.php', true],
    'App\\Controller\\CategoryCoursController::show' => ['privates', '.service_locator.ow6O9tX', 'get_ServiceLocator_Ow6O9tXService.php', true],
    'App\\Controller\\CoursController::delete' => ['privates', '.service_locator.D5mB_BZ', 'get_ServiceLocator_D5mBBZService.php', true],
    'App\\Controller\\CoursController::edit' => ['privates', '.service_locator.D5mB_BZ', 'get_ServiceLocator_D5mBBZService.php', true],
    'App\\Controller\\CoursController::index' => ['privates', '.service_locator.dnS3PVd', 'get_ServiceLocator_DnS3PVdService.php', true],
    'App\\Controller\\CoursController::show' => ['privates', '.service_locator.D5mB_BZ', 'get_ServiceLocator_D5mBBZService.php', true],
    'App\\Controller\\ProductController::newProduct' => ['privates', '.service_locator.tgLzJhk', 'get_ServiceLocator_TgLzJhkService.php', true],
    'App\\Controller\\QuestionController::delete' => ['privates', '.service_locator.6R9gNN2', 'get_ServiceLocator_6R9gNN2Service.php', true],
    'App\\Controller\\QuestionController::edit' => ['privates', '.service_locator.6R9gNN2', 'get_ServiceLocator_6R9gNN2Service.php', true],
    'App\\Controller\\QuestionController::index' => ['privates', '.service_locator.2nLzZDj', 'get_ServiceLocator_2nLzZDjService.php', true],
    'App\\Controller\\QuestionController::show' => ['privates', '.service_locator.6R9gNN2', 'get_ServiceLocator_6R9gNN2Service.php', true],
    'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.wyrb61.', 'get_ServiceLocator_Wyrb61_Service.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.GgSa1Ig', 'get_ServiceLocator_GgSa1IgService.php', true],
    'App\\Controller\\CategoryController:show' => ['privates', '.service_locator..JzDQIR', 'get_ServiceLocator__JzDQIRService.php', true],
    'App\\Controller\\CategoryCoursController:delete' => ['privates', '.service_locator.ow6O9tX', 'get_ServiceLocator_Ow6O9tXService.php', true],
    'App\\Controller\\CategoryCoursController:edit' => ['privates', '.service_locator.ow6O9tX', 'get_ServiceLocator_Ow6O9tXService.php', true],
    'App\\Controller\\CategoryCoursController:index' => ['privates', '.service_locator.UzvzYfm', 'get_ServiceLocator_UzvzYfmService.php', true],
    'App\\Controller\\CategoryCoursController:show' => ['privates', '.service_locator.ow6O9tX', 'get_ServiceLocator_Ow6O9tXService.php', true],
    'App\\Controller\\CoursController:delete' => ['privates', '.service_locator.D5mB_BZ', 'get_ServiceLocator_D5mBBZService.php', true],
    'App\\Controller\\CoursController:edit' => ['privates', '.service_locator.D5mB_BZ', 'get_ServiceLocator_D5mBBZService.php', true],
    'App\\Controller\\CoursController:index' => ['privates', '.service_locator.dnS3PVd', 'get_ServiceLocator_DnS3PVdService.php', true],
    'App\\Controller\\CoursController:show' => ['privates', '.service_locator.D5mB_BZ', 'get_ServiceLocator_D5mBBZService.php', true],
    'App\\Controller\\ProductController:newProduct' => ['privates', '.service_locator.tgLzJhk', 'get_ServiceLocator_TgLzJhkService.php', true],
    'App\\Controller\\QuestionController:delete' => ['privates', '.service_locator.6R9gNN2', 'get_ServiceLocator_6R9gNN2Service.php', true],
    'App\\Controller\\QuestionController:edit' => ['privates', '.service_locator.6R9gNN2', 'get_ServiceLocator_6R9gNN2Service.php', true],
    'App\\Controller\\QuestionController:index' => ['privates', '.service_locator.2nLzZDj', 'get_ServiceLocator_2nLzZDjService.php', true],
    'App\\Controller\\QuestionController:show' => ['privates', '.service_locator.6R9gNN2', 'get_ServiceLocator_6R9gNN2Service.php', true],
    'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.wyrb61.', 'get_ServiceLocator_Wyrb61_Service.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
