<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.7OHfgvt' shared service.

return $this->privates['.service_locator.7OHfgvt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'etudiantRepository' => ['privates', 'App\\Repository\\EtudiantRepository', 'getEtudiantRepositoryService.php', true],
    'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService.php', true],
]);
