<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator._ukRkc.' shared service.

return $this->privates['.service_locator._ukRkc.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'coursRepository' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService.php', true],
    'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService.php', true],
]);
