<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.5Pv2Gj6' shared service.

return $this->privates['.service_locator.5Pv2Gj6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'class' => ['privates', 'App\\Entity\\Classes', 'getClassesService.php', true],
]);
