<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Entity\Etudiant' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Entity\\Etudiant.php';

return $this->privates['App\\Entity\\Etudiant'] = new \App\Entity\Etudiant();
