<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ldZsI0_' shared service.

return $this->privates['.service_locator.ldZsI0_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'classesRepository' => ['privates', 'App\\Repository\\ClassesRepository', 'getClassesRepositoryService.php', true],
    'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService.php', true],
]);
