<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Entity\Cours' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Entity\\Cours.php';

return $this->privates['App\\Entity\\Cours'] = new \App\Entity\Cours();
