<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3zfChkv\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3zfChkv/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3zfChkv.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3zfChkv\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container3zfChkv\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '3zfChkv',
    'container.build_id' => '7d233281',
    'container.build_time' => 1563310667,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3zfChkv');
