<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRu53qfW\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRu53qfW/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRu53qfW.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRu53qfW\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRu53qfW\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ru53qfW',
    'container.build_id' => 'e4275ce1',
    'container.build_time' => 1561498212,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRu53qfW');
